"""empty message

Revision ID: 795aa400d2f6
Revises: f2660dd3a57c
Create Date: 2022-11-07 11:13:21.755566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795aa400d2f6'
down_revision = 'f2660dd3a57c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bike', sa.Column('cyclist_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'bike', 'cyclist', ['cyclist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bike', type_='foreignkey')
    op.drop_column('bike', 'cyclist_id')
    # ### end Alembic commands ###
